[colors.primary]
background = '#131314'
foreground = '#e4e2e3'
 
[colors.cursor]
text = '#e4e2e3'
cursor = '#c8c6c7' 
 
[colors.vi_mode_cursor]
text = '#131314'
cursor = '#bfc7d5' 
 
[colors.search.matches]
foreground = '#474648' 
background = '#bbc7db' 
 
[colors.search.focused_match]
foreground = '#474648' 
background = '#bfc7d5' 
 
[colors.footer_bar]
foreground = '#474648' 
background = '#e4e2e3' 
 
[colors.hints.start]
foreground = '#474648' 
background = '#c3c6cf' 
 
[colors.hints.end]
foreground = '#474648' 
background = '#c3c6cf' 
 
[colors.selection]
text = '#131314'
background = '#bfc7d5'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#0f61a4' 
yellow = '#313c4c' 
blue = '#71aff7' 
magenta = '#a1c9ff' 
cyan = '#a088ac' 
white = '#e4e2e3' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE'
