[colors.primary]
background = '#fbf9fa'
foreground = '#1b1b1d'
 
[colors.cursor]
text = '#1b1b1d'
cursor = '#474648' 
 
[colors.vi_mode_cursor]
text = '#fbf9fa'
cursor = '#575f6b' 
 
[colors.search.matches]
foreground = '#e4e2e3' 
background = '#535f70' 
 
[colors.search.focused_match]
foreground = '#e4e2e3' 
background = '#575f6b' 
 
[colors.footer_bar]
foreground = '#e4e2e3' 
background = '#303031' 
 
[colors.hints.start]
foreground = '#e4e2e3' 
background = '#5a5f66' 
 
[colors.hints.end]
foreground = '#e4e2e3' 
background = '#5a5f66' 
 
[colors.selection]
text = '#fbf9fa'
background = '#575f6b'
 
 
[colors.normal]
black = '#181818' 
red = '#ba1a1a' 
green = '#0f61a4' 
yellow = '#313c4c' 
blue = '#71aff7' 
magenta = '#a1c9ff' 
cyan = '#a088ac' 
white = '#1b1b1d' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE'
