# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#1b1b1d"

# Title color for boxes
theme[title]="#575f6b"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#5a5f66"

# Background color of selected item in processes box
theme[selected_bg]="#575f6b"

# Foreground color of selected item in processes box
theme[selected_fg]="#ffffff"

# Color of inactive/disabled text
theme[inactive_fg]="#474648"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#535f70"

# Cpu box outline color
theme[cpu_box]="#787778"

# Memory/disks box outline color
theme[mem_box]="#787778"

# Net up/down box outline color
theme[net_box]="#787778"

# Processes box outline color
theme[proc_box]="#787778"

# Box divider line and small boxes line color
theme[div_line]="#c8c6c7"

# Temperature graph colors
theme[temp_start]="#5a5f66"
theme[temp_mid]="#575f6b"
theme[temp_end]="#ba1a1a"

# CPU graph colors
theme[cpu_start]="#5a5f66"
theme[cpu_mid]="#575f6b"
theme[cpu_end]="#ba1a1a"

# Mem/Disk free meter
theme[free_start]="#5a5f66"
theme[free_mid]=""
theme[free_end]="#dfe2eb"

# Mem/Disk cached meter
theme[cached_start]="#535f70"
theme[cached_mid]=""
theme[cached_end]="#d7e3f8"

# Mem/Disk available meter
theme[available_start]="#575f6b"
theme[available_mid]=""
theme[available_end]="#dbe3f1"

# Mem/Disk used meter
theme[used_start]="#ba1a1a"
theme[used_mid]=""
theme[used_end]="#ffdad6"

# Download graph colors
theme[download_start]="#5a5f66"
theme[download_mid]="#575f6b"
theme[download_end]="#535f70"

# Upload graph colors
theme[upload_start]="#5a5f66"
theme[upload_mid]="#575f6b"
theme[upload_end]="#535f70"
