# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e4e2e3"

# Title color for boxes
theme[title]="#bfc7d5"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#c3c7cf"

# Background color of selected item in processes box
theme[selected_bg]="#bfc7d5"

# Foreground color of selected item in processes box
theme[selected_fg]="#29313c"

# Color of inactive/disabled text
theme[inactive_fg]="#c8c6c7"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#bbc7db"

# Cpu box outline color
theme[cpu_box]="#919092"

# Memory/disks box outline color
theme[mem_box]="#919092"

# Net up/down box outline color
theme[net_box]="#919092"

# Processes box outline color
theme[proc_box]="#919092"

# Box divider line and small boxes line color
theme[div_line]="#474748"

# Temperature graph colors
theme[temp_start]="#c3c7cf"
theme[temp_mid]="#bfc7d5"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#c3c7cf"
theme[cpu_mid]="#bfc7d5"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#c3c7cf"
theme[free_mid]=""
theme[free_end]="#42474e"

# Mem/Disk cached meter
theme[cached_start]="#bbc7db"
theme[cached_mid]=""
theme[cached_end]="#3b4858"

# Mem/Disk available meter
theme[available_start]="#bfc7d5"
theme[available_mid]=""
theme[available_end]="#3f4753"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#c3c7cf"
theme[download_mid]="#bfc7d5"
theme[download_end]="#bbc7db"

# Upload graph colors
theme[upload_start]="#c3c7cf"
theme[upload_mid]="#bfc7d5"
theme[upload_end]="#bbc7db"
