"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](bg:#b3c5ff)\
[ 󰣇 ](bg:#b3c5ff fg:#101114)\
[](bg:#718ee0 fg:#b3c5ff)\
$directory\
[](fg:#718ee0 bg:#21428f)\
$git_branch\
$git_status\
[](fg:#21428f bg:#303034)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#303034 bg:#252629)\
$time\
[ ](fg:#252629)\
\n$character"""

scan_timeout = 500
command_timeout = 2000

[directory]
style = "fg:#e4e2e6 bg:#718ee0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#21428f"
format = '[[ $symbol $branch ](fg:#718ee0 bg:#21428f)]($style)'

[git_status]
style = "bg:#21428f"
format = '[[($all_status$ahead_behind )](fg:#718ee0 bg:#21428f)]($style)'

[nodejs]
symbol = ""
style = "bg:#303034"
format = '[[ $symbol ($version) ](fg:#718ee0 bg:#303034)]($style)'

[rust]
symbol = ""
style = "bg:#303034"
format = '[[ $symbol ($version) ](fg:#718ee0 bg:#303034)]($style)'

[golang]
symbol = ""
style = "bg:#303034"
format = '[[ $symbol ($version) ](fg:#718ee0 bg:#303034)]($style)'

[php]
symbol = ""
style = "bg:#303034"
format = '[[ $symbol ($version) ](fg:#718ee0 bg:#303034)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#252629"
format = '[[  $time ](fg:#aaaab4 bg:#252629)]($style)'
