"$schema" = 'https://starship.rs/config-schema.json'
format = """
[░▒▓](fg:#a1c9ff)\
[ 󰣇 ](bg:#a1c9ff fg:#0f1114)\
[](fg:#a1c9ff bg:#5594db)\
$directory\
[](fg:#5594db bg:#004880)\
$git_branch\
$git_status\
[](fg:#004880 bg:#2f3033)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#2f3033 bg:#242629)\
$time\
[](fg:#242629)\
\n$character"""

scan_timeout = 500
command_timeout = 2000

[directory]
style = "fg:#e3e2e6 bg:#5594db"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = "󰉏 "

[git_branch]
symbol = "󰘬"
style = "bg:#004880"
format = '[[ $symbol $branch ](fg:#5594db bg:#004880)]($style)'

[git_status]
style = "bg:#004880"
format = '[[($all_status$ahead_behind )](fg:#5594db bg:#004880)]($style)'
conflicted = "󰞇 "
ahead = "󰁝${count} "
behind = "󰁅${count} "
diverged = "󰹺 "
untracked = "󰄱 "
stashed = "󰆓 "
modified = "󰷈 "
staged = "󰐕 "
renamed = "󰑕 "
deleted = "󰮉 "

[nodejs]
symbol = "󰎙"
style = "bg:#2f3033"
format = '[[ $symbol ($version) ](fg:#5594db bg:#2f3033)]($style)'

[rust]
symbol = "󱘗"
style = "bg:#2f3033"
format = '[[ $symbol ($version) ](fg:#5594db bg:#2f3033)]($style)'

[golang]
symbol = "󰟓"
style = "bg:#2f3033"
format = '[[ $symbol ($version) ](fg:#5594db bg:#2f3033)]($style)'

[php]
symbol = "󰌟"
style = "bg:#2f3033"
format = '[[ $symbol ($version) ](fg:#5594db bg:#2f3033)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#242629"
format = '[[  $time ](fg:#a7abb4 bg:#242629)]($style)'

[character]
success_symbol = "[❯](bold fg:#5594db)"
error_symbol = "[❯](bold fg:#ff5f5f)"
vimcmd_symbol = "[❮](bold fg:#5594db)"
